WITH CHEAPESTPRODUCTS AS (
    SELECT
        PS.PRODUCT_ID,
        PS.SUPPLIER_ID,
        P.DESCRIPTION,
        P.PRICE,
        ROW_NUMBER() OVER (PARTITION BY PS.SUPPLIER_ID ORDER BY P.PRICE) AS "ROWNUM"
    FROM
        PRODUCT_SUPPLIER PS
        JOIN PRODUCT P ON PS.PRODUCT_ID = P.PRODUCT_ID
)
SELECT
    S.SUPPLIER_ID,
    S.COUNTRY,
    S.NAME,
    CP.PRODUCT_ID,
    CP.DESCRIPTION,
    CP.PRICE
FROM
    SUPPLIER S
JOIN
    CHEAPESTPRODUCTS CP ON S.SUPPLIER_ID = CP.SUPPLIER_ID
WHERE
    CP."ROWNUM" = 1;
