SELECT
    S.SUPPLIER_ID,
    S.COUNTRY,
    S.NAME,
    P.PRODUCT_ID,
    P.DESCRIPTION,
    P.PRICE,
    PR.PRICE_REDUCTION_ID,
    PR.END_DATE,
    PR.REDUCED_PRICE,
    PR.START_DATE
FROM
    SUPPLIER S
JOIN
    PRODUCT_SUPPLIER PS ON S.SUPPLIER_ID = PS.SUPPLIER_ID
JOIN
    PRODUCT P ON PS.PRODUCT_ID = P.PRODUCT_ID
JOIN
    PRICE_REDUCTION PR ON P.PRICE_REDUCTIONFK = PR.PRICE_REDUCTION_ID
WHERE
    CURRENT_DATE BETWEEN PR.START_DATE AND PR.END_DATE;

